--Cantidad de vuelos por mes
SELECT TO_CHAR(FECHA_HORA_PARTIDA, 'YYYY-MM'), COUNT(*)
FROM TBL_VUELOS
GROUP BY TO_CHAR(FECHA_HORA_PARTIDA, 'YYYY-MM');

--Cantidad de pasajeros por clases sociales
SELECT A.CODIGO_VUELO,B.NOMBRE_CLASE, COUNT(*) CANTIDAD_PASAJEROS
FROM TBL_FACTURA_DETALLE A
INNER JOIN TBL_CLASES_SOCIALES B
ON (A.CODIGO_CLASE = B.CODIGO_CLASE)
GROUP BY A.CODIGO_VUELO,B.NOMBRE_CLASE
ORDER BY CODIGO_VUELO, NOMBRE_CLASE;

--Lista de tripulantes de un vuelo especifico
SELECT  A.CODIGO_VUELO, 
        B.NOMBRE, 
        C.NOMBRE_CARGO
FROM TBL_TRIPULACION_X_VUELOS A
INNER JOIN TBL_TRIPULACION B
ON (A.CODIGO_TRIPULANTE = B.CODIGO_TRIPULANTE)
INNER JOIN TBL_CARGOS_TRIPULANTES C
ON (B.CODIGO_CARGO = C.CODIGO_CARGO)
WHERE A.CODIGO_VUELO =  1;

--Jerarquia de la tripulacion
SELECT A.NOMBRE,
      B.NOMBRE AS NOMBRE_SUPERIOR
FROM TBL_TRIPULACION A
LEFT JOIN TBL_TRIPULACION B
ON (A.CODIGO_TRIPULANTE_SUPERIOR = B.CODIGO_TRIPULANTE);



--

--Cantidad de asientos por vuelo
SELECT A.CODIGO_VUELO, B.CANTIDAD_ASIENTOS
FROM TBL_VUELOS A
INNER JOIN TBL_AVIONES B
ON (A.CODIGO_AVION = B.CODIGO_AVION);

--Cantidad de asientos ocupados
SELECT CODIGO_VUELO, COUNT(*)
FROM TBL_FACTURA_DETALLE
GROUP BY CODIGO_VUELO;

--ASIENTOS DISPONIBLES
SELECT A.CODIGO_VUELO,
      CANTIDAD_TOTAL,
      NVL(CANTIDAD_OCUPADOS,0) AS CANTIDAD_OCUPADOS,
      CANTIDAD_TOTAL-NVL(CANTIDAD_OCUPADOS,0) AS CANTIDAD_DISPONIBLES
FROM (
      SELECT A.CODIGO_VUELO, 
          B.CANTIDAD_ASIENTOS AS CANTIDAD_TOTAL
      FROM TBL_VUELOS A
      INNER JOIN TBL_AVIONES B
      ON (A.CODIGO_AVION = B.CODIGO_AVION)
    ) A
LEFT JOIN (
      SELECT CODIGO_VUELO, COUNT(*) CANTIDAD_OCUPADOS
      FROM TBL_FACTURA_DETALLE
      GROUP BY CODIGO_VUELO
) B
ON (A.CODIGO_VUELO = B.CODIGO_VUELO);



--OCUPADOS
VUELO 1: 8
--TOTALES
VUELO 1: 100
--DISPONIBLES
RESULTADO: 92