--Calcular la cantidad de escalas o puntos por VUELO

SELECT A.CODIGO_VUELO, COUNT(*) ESCALAS
FROM tbl_vuelos A
INNER JOIN TBL_RUTAS B
ON (A.CODIGO_RUTA = B.CODIGO_RUTA)
INNER JOIN TBL_PUNTOS_X_RUTAS C
ON (B.CODIGO_RUTA = C.CODIGO_RUTA)
GROUP BY A.CODIGO_VUELO;


--Porcentaje de cada clase social por cada vuelo.
--Pasajeros por vuelo y clase
SELECT A.CODIGO_VUELO,
      B.NOMBRE_CLASE, 
     COUNT(*) CANTIDAD_PASAJEROS
FROM TBL_FACTURA_DETALLE A
INNER JOIN TBL_CLASES_SOCIALES B
ON (A.CODIGO_CLASE = B.CODIGO_CLASE)
GROUP BY A.CODIGO_VUELO,
      B.NOMBRE_CLASE;
      
--Pasajeros por vuelo
SELECT CODIGO_VUELO, COUNT(*) PASAJEROS_VUELO
FROM TBL_FACTURA_DETALLE
GROUP BY CODIGO_VUELO;

--Investigacion de Kevin
--listagg(porCENTAJE, ',')
--pivot, unpivot

--Resultado
SELECT A.CODIGO_VUELO, A.NOMBRE_CLASE, A.CANTIDAD_PASAJEROS,
        B.PASAJEROS_VUELO,
        ROUND((CANTIDAD_PASAJEROS/PASAJEROS_VUELO)*100,2) || '%' AS PORCENTAJE
FROM (
    SELECT A.CODIGO_VUELO,
          B.NOMBRE_CLASE, 
         COUNT(*) CANTIDAD_PASAJEROS
    FROM TBL_FACTURA_DETALLE A
    INNER JOIN TBL_CLASES_SOCIALES B
    ON (A.CODIGO_CLASE = B.CODIGO_CLASE)
    GROUP BY A.CODIGO_VUELO,
          B.NOMBRE_CLASE
) A
INNER JOIN (
    SELECT CODIGO_VUELO, COUNT(*) PASAJEROS_VUELO
    FROM TBL_FACTURA_DETALLE
    GROUP BY CODIGO_VUELO
) B
ON (A.CODIGO_VUELO = B.CODIGO_VUELO)
ORDER BY CODIGO_VUELO;





