SELECT *
FROM EMPLOYEES
WHERE hire_date between 
      TO_DATE('01-01-2005','DD-MM-YYYY') AND
      TO_DATE('31-12-2005','DD-MM-YYYY');
      
SELECT *
FROM EMPLOYEES
WHERE TO_CHAR(hire_date,'YYYY') = 2005;


CREATE TABLE TBL_EMPLOYEES_2005 AS
SELECT *
FROM EMPLOYEES
WHERE TO_CHAR(hire_date,'YYYY') = 2005;

INSERT INTO TBL_EMPLOYEES_2004(
      EMPLOYEE_ID,FIRST_NAME,
      LAST_NAME,EMAIL,
      PHONE_NUMBER,HIRE_DATE,
      JOB_ID,SALARY,
      COMMISSION_PCT,MANAGER_ID,
      DEPARTMENT_ID)
SELECT EMPLOYEE_ID,FIRST_NAME,
      LAST_NAME,EMAIL,
      PHONE_NUMBER,HIRE_DATE,
      JOB_ID,SALARY,
      COMMISSION_PCT,MANAGER_ID,
      DEPARTMENT_ID
FROM EMPLOYEES
WHERE TO_CHAR(hire_date,'YYYY') = 2004;


SELECT *
FROM TBL_EMPLOYEES_2004;

SELECT *
FROM TBL_EMPLOYEES_2005;



SELECT * FROM TBL_EMPLOYEES_2005;
SELECT * FROM TBL_EMPLOYEES_2004;

