--Consulta de tablas independientes
SELECT * 
FROM EMPLOYEES;

SELECT * 
FROM JOBS;

--Super consulta
SELECT A.FIRST_NAME || ' ' || A.LAST_NAME AS NAME,
      A.EMAIL,
      A.PHONE_NUMBER,
      A.HIRE_DATE,
      A.SALARY,
      C.JOB_TITLE,
      E.DEPARTMENT_NAME,
      F.CITY AS DEPARTMENT_CITY,
      G.COUNTRY_NAME AS DEPARTMENT_COUNTRY_NAME,
      H.REGION_NAME AS DEPARTMENT_REGION_NAME,
      B.FIRST_NAME || ' ' || B.LAST_NAME AS MANAGER_NAME,
      D.JOB_TITLE AS MANAGER_JOB_TITLE
FROM EMPLOYEES A
LEFT JOIN EMPLOYEES B
ON (A.MANAGER_ID = B.EMPLOYEE_ID)
INNER JOIN JOBS C
  ON (A.JOB_ID = C.JOB_ID)
LEFT JOIN JOBS D
  ON (B.JOB_ID = D.JOB_ID)
LEFT JOIN DEPARTMENTS E
  ON (A.DEPARTMENT_ID = E.DEPARTMENT_ID)
LEFT JOIN LOCATIONS F
  ON (E.LOCATION_ID = F.LOCATION_ID)
LEFT JOIN COUNTRIES G
  ON (F.COUNTRY_ID = G.COUNTRY_ID)
LEFT JOIN REGIONS H
  ON (G.REGION_ID = H.REGION_ID);



----Creacion de una vista (DDL):
CREATE OR REPLACE VIEW VW_EMPLOYEES AS
SELECT A.FIRST_NAME || ' ' || A.LAST_NAME AS NAME,
      A.EMAIL,
      A.PHONE_NUMBER,
      A.HIRE_DATE,
      A.SALARY,
      C.JOB_TITLE,
      E.DEPARTMENT_NAME,
      F.CITY AS DEPARTMENT_CITY,
      G.COUNTRY_NAME AS DEPARTMENT_COUNTRY_NAME,
      H.REGION_NAME AS DEPARTMENT_REGION_NAME,
      B.FIRST_NAME || ' ' || B.LAST_NAME AS MANAGER_NAME,
      D.JOB_TITLE AS MANAGER_JOB_TITLE
FROM EMPLOYEES A
LEFT JOIN EMPLOYEES B
ON (A.MANAGER_ID = B.EMPLOYEE_ID)
INNER JOIN JOBS C
  ON (A.JOB_ID = C.JOB_ID)
LEFT JOIN JOBS D
  ON (B.JOB_ID = D.JOB_ID)
LEFT JOIN DEPARTMENTS E
  ON (A.DEPARTMENT_ID = E.DEPARTMENT_ID)
LEFT JOIN LOCATIONS F
  ON (E.LOCATION_ID = F.LOCATION_ID)
LEFT JOIN COUNTRIES G
  ON (F.COUNTRY_ID = G.COUNTRY_ID)
LEFT JOIN REGIONS H
  ON (G.REGION_ID = H.REGION_ID);


SELECT * 
FROM VW_EMPLOYEES;



/* Por curiosidad de Kevin
select lpad('      ',level, 5) || first_name
from EMPLOYEES
connect by prior employee_id = manager_id
start with manager_id is null;*/





