INSERT INTO TBL_EMPLOYEES_2005
SELECT *
FROM TBL_EMPLOYEES_2004
WHERE employee_id = 201;


INSERT INTO SUCURSALES (CAMPOS)
SELECT CAMPOS
FROM SUCURSAL1
UNION ALL
SELECT CAMPOS
FROM SUCURSAL2
UNION ALL
SELECT CAMPOS
FROM SUCURSAL3;










SELECT employee_id, first_name, last_name
FROM TBL_EMPLOYEES_2004
UNION ALL
SELECT employee_id, first_name, last_name
FROM TBL_EMPLOYEES_2005
;



SELECT employee_id, first_name, last_name
FROM TBL_EMPLOYEES_2004
INTERSECT
SELECT employee_id, first_name, last_name
FROM TBL_EMPLOYEES_2005;

SELECT A.*
FROM TBL_EMPLOYEES_2004 A
INNER JOIN TBL_EMPLOYEES_2005 B
ON (A.EMPLOYEE_ID = B.EMPLOYEE_ID);




SELECT employee_id, first_name, last_name
FROM TBL_EMPLOYEES_2004
MINUS
SELECT employee_id, first_name, last_name
FROM TBL_EMPLOYEES_2005;


SELECT A.*,B.*
FROM TBL_EMPLOYEES_2004 A
LEFT JOIN TBL_EMPLOYEES_2005 B
ON (A.EMPLOYEE_ID = B.EMPLOYEE_ID)
WHERE B.EMPLOYEE_ID IS NULL;