--Procedimiento almacenado para insertar en la tabla de productos

CREATE SEQUENCE SQ_CODIGO_PRODUCTO;

CREATE OR REPLACE PROCEDURE SP_INSERTAR_PRODUCTO(
      P_CODIGO_MARCA IN INTEGER,
      P_CODIGO_CATEGORIA IN INTEGER,
      P_NOMBRE_PRODUCTO IN VARCHAR2,
      P_PRECIO IN NUMBER,
      P_EXISTENCIA IN NUMBER,
      P_CODIGO_PRODUCTO OUT NUMBER,
      P_MENSAJE_RESULTADO OUT VARCHAR2) AS
BEGIN
  --SELECT SQ_CODIGO_PRODUCTO.NEXTVAL INTO P_CODIGO_PRODUCTO FROM DUAL;
  P_CODIGO_PRODUCTO := SQ_CODIGO_PRODUCTO.NEXTVAL;
  INSERT INTO TBL_PRODUCTOS
    (
      CODIGO_PRODUCTO,
      CODIGO_MARCA,
      CODIGO_CATEGORIA,
      NOMBRE_PRODUCTO,
      PRECIO,
      EXISTENCIA
    )
  VALUES
    (
      P_CODIGO_PRODUCTO,
      P_CODIGO_MARCA,
      P_CODIGO_CATEGORIA,
      P_NOMBRE_PRODUCTO,
      P_PRECIO,
      P_EXISTENCIA
     );
  COMMIT;
  EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error al insertar: '||SQLERRM||' : '||SQLCODE);
    P_MENSAJE_RESULTADO := 'Error al insertar: '||SQLERRM||' : '||SQLCODE;
    ROLLBACK;
END;


EXECUTE SP_INSERTAR_PRODUCTO();
CALL SP_INSERTAR_PRODUCTO();

--Ejecutar procedimiento almacenado y obtener los valores de los parametros de salida
set serveroutput on;

DECLARE
  V_CODIGO_PRODUCTO INTEGER;
  V_MENSAJE_RESULTADO VARCHAR2(200);
BEGIN
  SP_INSERTAR_PRODUCTO(1,1,'PRODUCTO DESDE UN PROCEDIMIENTO',
  1234,100, V_CODIGO_PRODUCTO,V_MENSAJE_RESULTADO);
  DBMS_OUTPUT.PUT_LINE('Codigo insertado: '||V_CODIGO_PRODUCTO);
END;


SELECT * FROM TBL_PRODUCTOS;

SELECT SQ_CODIGO_PRODUCTO.NEXTVAL FROM TBL_PRODUCTOS;
